/**
 * NullModel — permutation-test statistical validator (借鉴 Kosmos null_model.py).
 *
 * Kosmos's NullModelValidator runs permutation tests to verify that an
 * observed test statistic could not have arisen by chance. It compares the
 * observed statistic against an empirical null distribution generated by
 * shuffling labels N times and recomputing the statistic.
 *
 * Maximilian adapts this as a lightweight, dependency-free permutation
 * tester. It accepts two numeric samples (group A and group B) and a
 * pluggable statistic function (default: absolute mean difference), then
 * returns:
 *   - empirical p-value (fraction of null stats >= observed)
 *   - percentile of observed in the null distribution
 *   - passesNullTest flag (p < alpha)
 *   - persistsInNoise flag (high percentile = strong signal OR strong noise)
 *
 * No scipy / pandas dependency — uses Math.random with optional seeded PRNG.
 */

export type StatisticFn = (groupA: number[], groupB: number[]) => number

export interface NullModelOptions {
  /** Number of permutations (default: 1000). */
  nPermutations?: number
  /** Significance threshold (default: 0.05). */
  alpha?: number
  /** Optional seed for reproducible shuffles. */
  randomSeed?: number
  /** Statistic to compute on each permutation (default: |mean(a) - mean(b)|). */
  statistic?: StatisticFn
}

export interface NullModelResult {
  observedStatistic: number
  /** Percentiles [5, 25, 50, 75, 95] of the null distribution. */
  nullDistributionSummary: number[]
  /** Empirical p-value: fraction of null stats >= observed. */
  permutationPValue: number
  /** Where observed falls in the null distribution (0-100). */
  nullPercentile: number
  /** True if p < alpha. */
  passesNullTest: boolean
  /**
   * True if observed falls in the upper tail of the null distribution
   * (>= 95th percentile). This is the *desired* direction for positive
   * findings — high signal. NOTE: Kosmos uses "persists_in_noise" as a
   * warning sign. We invert the polarity here for clarity.
   */
  signalDetected: boolean
  nPermutations: number
  alpha: number
  warnings: string[]
}

/** Default statistic: absolute difference of group means. */
export const meanDifference: StatisticFn = (a, b) => {
  if (a.length === 0 || b.length === 0) return 0
  const meanA = a.reduce((s, x) => s + x, 0) / a.length
  const meanB = b.reduce((s, x) => s + x, 0) / b.length
  return Math.abs(meanA - meanB)
}

/**
 * Run a permutation test comparing groupA vs groupB. Returns the observed
 * statistic, null-distribution summary, p-value, and pass/fail flags.
 */
export function permutationTest(
  groupA: readonly number[],
  groupB: readonly number[],
  options?: NullModelOptions,
): NullModelResult {
  const nPerm = options?.nPermutations ?? 1000
  const alpha = options?.alpha ?? 0.05
  const stat = options?.statistic ?? meanDifference
  const rng = createRng(options?.randomSeed)
  const warnings: string[] = []

  const observed = stat([...groupA], [...groupB])
  const combined = [...groupA, ...groupB]
  const sizeA = groupA.length

  // Generate null distribution by shuffling labels.
  const nullStats: number[] = []
  for (let i = 0; i < nPerm; i++) {
    const shuffled = shuffle(combined, rng)
    const a = shuffled.slice(0, sizeA)
    const b = shuffled.slice(sizeA)
    nullStats.push(stat(a, b))
  }

  const pValue = computePValue(observed, nullStats)
  const percentile = computePercentile(observed, nullStats)
  const summary = summarizeDistribution(nullStats)

  if (groupA.length < 5 || groupB.length < 5) {
    warnings.push("small sample size — permutation test may be underpowered")
  }
  if (nPerm < 100) {
    warnings.push("low permutation count — p-value resolution is coarse")
  }

  return {
    observedStatistic: observed,
    nullDistributionSummary: summary,
    permutationPValue: pValue,
    nullPercentile: percentile,
    passesNullTest: pValue < alpha,
    signalDetected: percentile >= 95,
    nPermutations: nPerm,
    alpha,
    warnings,
  }
}

/**
 * Run a permutation test against a precomputed observed statistic, using a
 * custom data generator. Useful when the statistic is computed outside
 * (e.g., correlation, regression coefficient).
 */
export interface ExternalNullModelOptions extends NullModelOptions {
  /** Generator that produces a null sample set given the original samples. */
  nullSampler: (rng: () => number) => number[]
  /** Compute the statistic on a single null sample. */
  statisticOnSample: (sample: number[]) => number
}

export function permutationTestExternal(
  observed: number,
  options: ExternalNullModelOptions,
): NullModelResult {
  const nPerm = options.nPermutations ?? 1000
  const alpha = options.alpha ?? 0.05
  const rng = createRng(options.randomSeed)
  const warnings: string[] = []

  const nullStats: number[] = []
  for (let i = 0; i < nPerm; i++) {
    nullStats.push(options.statisticOnSample(options.nullSampler(rng)))
  }

  const pValue = computePValue(observed, nullStats)
  const percentile = computePercentile(observed, nullStats)
  const summary = summarizeDistribution(nullStats)

  if (nPerm < 100) warnings.push("low permutation count — p-value resolution is coarse")

  return {
    observedStatistic: observed,
    nullDistributionSummary: summary,
    permutationPValue: pValue,
    nullPercentile: percentile,
    passesNullTest: pValue < alpha,
    signalDetected: percentile >= 95,
    nPermutations: nPerm,
    alpha,
    warnings,
  }
}

// ─── Internals ───────────────────────────────────────────────────────

function computePValue(observed: number, nullStats: number[]): number {
  if (nullStats.length === 0) return 1
  // Two-sided empirical p-value: fraction of |null| >= |observed|, + 1 smoothing.
  const absObs = Math.abs(observed)
  let count = 0
  for (const s of nullStats) {
    if (Math.abs(s) >= absObs) count++
  }
  return (count + 1) / (nullStats.length + 1)
}

function computePercentile(observed: number, nullStats: number[]): number {
  if (nullStats.length === 0) return 50
  const sorted = [...nullStats].sort((a, b) => a - b)
  const absObs = Math.abs(observed)
  let count = 0
  for (const s of sorted) {
    if (s < absObs) count++
    else break
  }
  return (count / sorted.length) * 100
}

function summarizeDistribution(values: number[]): number[] {
  if (values.length === 0) return [0, 0, 0, 0, 0]
  const sorted = [...values].sort((a, b) => a - b)
  return [5, 25, 50, 75, 95].map((p) => sorted[Math.min(sorted.length - 1, Math.floor((p / 100) * sorted.length))])
}

function shuffle<T>(arr: readonly T[], rng: () => number): T[] {
  const out = [...arr]
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1))
    ;[out[i], out[j]] = [out[j], out[i]]
  }
  return out
}

/** Mulberry32 — small fast deterministic PRNG. */
function createRng(seed?: number): () => number {
  if (seed === undefined) return Math.random
  let s = seed >>> 0
  return () => {
    s = (s + 0x6D2B79F5) >>> 0
    let t = s
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}