// Copyright (c) 2026 Maximilian contributors
// SPDX-License-Identifier: MIT
//
// Licensed under the MIT License. See LICENSE in the project root.

/**
 * ai-elements — reusable assistant message-part widgets (ZCode
 * ai-elements borrowing). Barrel export: one widget per file, each backed
 * by the pure coercion functions in ./model and the aiElements i18n
 * domain (src/locales/ai-elements.*.json).
 */
export { CodeBlock } from "./CodeBlock"
export type { CodeBlockProps } from "./CodeBlock"
export { ReasoningBlock } from "./ReasoningBlock"
export type { ReasoningBlockProps } from "./ReasoningBlock"
export { AttachmentCard } from "./AttachmentCard"
export type { AttachmentCardProps } from "./AttachmentCard"
export { CitationBlock } from "./CitationBlock"
export type { CitationBlockProps } from "./CitationBlock"
export { KeyValueCard } from "./KeyValueCard"
export type { KeyValueCardProps } from "./KeyValueCard"
export { ImagePreviewBlock } from "./ImagePreviewBlock"
export type { ImagePreviewBlockProps } from "./ImagePreviewBlock"
export { ErrorBlock } from "./ErrorBlock"
export type { ErrorBlockProps } from "./ErrorBlock"
export { TokenUsageBadge } from "./TokenUsageBadge"
export type { TokenUsageBadgeProps } from "./TokenUsageBadge"
export { LatencyMeter } from "./LatencyMeter"
export type { LatencyMeterProps } from "./LatencyMeter"
export { StatusPill } from "./StatusPill"
export type { StatusPillProps } from "./StatusPill"
export { StreamingCursor } from "./StreamingCursor"
export type { StreamingCursorProps } from "./StreamingCursor"
export { DocumentPreviewBlock } from "./DocumentPreviewBlock"
export type { DocumentPreviewBlockProps } from "./DocumentPreviewBlock"
export { MarkdownProseBlock } from "./MarkdownProseBlock"
export type { MarkdownProseBlockProps } from "./MarkdownProseBlock"
export { ToolResultBlock } from "./ToolResultBlock"
export type { ToolResultBlockProps } from "./ToolResultBlock"
export { PlanStepList } from "./PlanStepList"
export type { PlanStepListProps } from "./PlanStepList"
export { TodoListBlock } from "./TodoListBlock"
export type { TodoListBlockProps } from "./TodoListBlock"
export { FileChangeCard } from "./FileChangeCard"
export type { FileChangeCardProps } from "./FileChangeCard"
export { TerminalOutputBlock } from "./TerminalOutputBlock"
export type { TerminalOutputBlockProps } from "./TerminalOutputBlock"
export { WebSearchBlock } from "./WebSearchBlock"
export type { WebSearchBlockProps } from "./WebSearchBlock"
export { LinkPreviewCard } from "./LinkPreviewCard"
export type { LinkPreviewCardProps } from "./LinkPreviewCard"
export { CommandBlock } from "./CommandBlock"
export type { CommandBlockProps } from "./CommandBlock"
export { TableBlock } from "./TableBlock"
export type { TableBlockProps } from "./TableBlock"
export { ProgressBlock } from "./ProgressBlock"
export type { ProgressBlockProps } from "./ProgressBlock"
export { AlertBanner } from "./AlertBanner"
export type { AlertBannerProps } from "./AlertBanner"
export { QuoteBlock } from "./QuoteBlock"
export type { QuoteBlockProps } from "./QuoteBlock"
export { DiffStat } from "./DiffStat"
export type { DiffStatProps } from "./DiffStat"
export { Collapse } from "./Collapse"
export type { CollapseProps } from "./Collapse"
export { Sparkline } from "./Sparkline"
export type { SparklineProps } from "./Sparkline"
export { BarMini } from "./BarMini"
export type { BarMiniProps } from "./BarMini"
export { DonutStat } from "./DonutStat"
export type { DonutStatProps } from "./DonutStat"
export { HeatRow } from "./HeatRow"
export type { HeatRowProps } from "./HeatRow"
export { GaugeArc } from "./GaugeArc"
export type { GaugeArcProps } from "./GaugeArc"
export { TimelineMini } from "./TimelineMini"
export type { TimelineMiniProps } from "./TimelineMini"
export { StatCard } from "./StatCard"
export type { StatCardProps } from "./StatCard"
export { DeltaBadge } from "./DeltaBadge"
export type { DeltaBadgeProps } from "./DeltaBadge"
export { CountUp } from "./CountUp"
export type { CountUpProps } from "./CountUp"
export { SkeletonBlock } from "./SkeletonBlock"
export type { SkeletonBlockProps } from "./SkeletonBlock"
export { EmptyHint } from "./EmptyHint"
export type { EmptyHintProps } from "./EmptyHint"
export { CopyField } from "./CopyField"
export type { CopyFieldProps } from "./CopyField"
export { JsonPeek } from "./JsonPeek"
export type { JsonPeekProps } from "./JsonPeek"

// Model layer — re-exported so consumers never import deep paths.
export * from "./model"
