/**
 * Provider presets — the curated list of LLM providers Maximilian can talk to.
 *
 * Borrowed wholesale from CC Switch's preset database
 * (https://github.com/farion1231/cc-switch). Each entry is an LLM
 * backend's static metadata (id / endpoint / apiFormat / default model /
 * category). No API keys live here — the registry reads them from env
 * vars per `envKey`.
 *
 * Categories:
 *   - official        Anthropic, OpenAI, Google — first-party LLM vendors
 *   - china           Chinese 1P vendors (DeepSeek, Zhipu, Moonshot, ...)
 *   - international   non-Chinese 1P vendors (Mistral, Cohere, Groq, ...)
 *   - aggregator      routing / aggregation services (OpenRouter, ...)
 *   - cloud           cloud-hosted proxies (AWS Bedrock, Azure OpenAI)
 *   - custom          user-defined endpoints
 *
 * OAuth-only presets (GitHub Copilot, ChatGPT Codex) are present but marked
 * `hidden: true` because they need an OAuth flow we do not yet implement.
 * Mark them visible once the OAuth broker ships.
 *
 * To add a preset: append to the matching category section below.
 * To remove: delete the entry. No registry code changes required.
 */

import type { ProviderPreset } from "./types.js"

/* eslint-disable @typescript-eslint/comma-dangle */

export const PROVIDER_PRESETS: ProviderPreset[] = [
  // ──────────────── official (first-party LLM vendors) ────────────────
  {
    id: "anthropic",
    name: "Anthropic Claude",
    envKey: "ANTHROPIC_API_KEY",
    envModel: "ANTHROPIC_MODEL",
    apiFormat: "anthropic",
    baseUrl: "https://api.anthropic.com",
    defaultModel: "claude-sonnet-4-5",
    websiteUrl: "https://www.anthropic.com",
    apiKeyUrl: "https://console.anthropic.com/settings/keys",
    category: "official",
    isOfficial: true,
  },
  {
    id: "openai",
    name: "OpenAI",
    envKey: "OPENAI_API_KEY",
    envModel: "OPENAI_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.openai.com/v1",
    defaultModel: "gpt-4o-mini",
    websiteUrl: "https://openai.com",
    apiKeyUrl: "https://platform.openai.com/api-keys",
    category: "official",
    isOfficial: true,
  },
  {
    id: "google",
    name: "Google Gemini",
    envKey: "GOOGLE_API_KEY",
    envModel: "GOOGLE_MODEL",
    apiFormat: "gemini_native",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    defaultModel: "gemini-2.5-flash",
    websiteUrl: "https://ai.google.dev",
    apiKeyUrl: "https://aistudio.google.com/app/apikey",
    category: "official",
    isOfficial: true,
  },

  // ──────────────── china (Chinese 1P LLM vendors) ────────────────
  {
    id: "deepseek",
    name: "DeepSeek",
    envKey: "DEEPSEEK_API_KEY",
    envModel: "DEEPSEEK_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.deepseek.com/v1",
    defaultModel: "deepseek-chat",
    websiteUrl: "https://platform.deepseek.com",
    apiKeyUrl: "https://platform.deepseek.com/api_keys",
    category: "china",
    isOfficial: true,
  },
  {
    id: "zhipu",
    name: "Zhipu GLM",
    envKey: "ZHIPU_API_KEY",
    envModel: "ZHIPU_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    defaultModel: "glm-4-plus",
    websiteUrl: "https://open.bigmodel.cn",
    apiKeyUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    category: "china",
    isOfficial: true,
  },
  {
    id: "dashscope",
    name: "Alibaba Bailian (Qwen)",
    envKey: "DASHSCOPE_API_KEY",
    envModel: "DASHSCOPE_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    defaultModel: "qwen-plus",
    websiteUrl: "https://bailian.console.aliyun.com",
    apiKeyUrl: "https://bailian.console.aliyun.com/#/api-key",
    category: "china",
    isOfficial: true,
  },
  {
    id: "moonshot",
    name: "Moonshot Kimi",
    envKey: "MOONSHOT_API_KEY",
    envModel: "MOONSHOT_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.moonshot.cn/v1",
    defaultModel: "moonshot-v1-128k",
    websiteUrl: "https://platform.moonshot.cn",
    apiKeyUrl: "https://platform.moonshot.cn/console/api-keys",
    category: "china",
    isOfficial: true,
    isPartner: true,
  },
  {
    id: "doubao",
    name: "ByteDance Doubao (Volcano Ark)",
    envKey: "DOUBAO_API_KEY",
    envModel: "DOUBAO_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    defaultModel: "doubao-pro-256k",
    websiteUrl: "https://www.volcengine.com/product/doubao",
    apiKeyUrl: "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
    category: "china",
    isOfficial: true,
  },
  {
    id: "baidu-qianfan",
    name: "Baidu Qianfan",
    envKey: "QIANFAN_API_KEY",
    envModel: "QIANFAN_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://qianfan.baidubce.com/v2",
    defaultModel: "ernie-4.5-8k",
    websiteUrl: "https://cloud.baidu.com/product/qianfan",
    apiKeyUrl: "https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application",
    category: "china",
    isOfficial: true,
  },
  {
    id: "yi",
    name: "Lingyi Yi (零一万物)",
    envKey: "YI_API_KEY",
    envModel: "YI_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.lingyiwanwu.com/v1",
    defaultModel: "yi-large",
    websiteUrl: "https://platform.lingyiwanwu.com",
    category: "china",
    isOfficial: true,
  },
  {
    id: "stepfun",
    name: "StepFun (阶跃星辰)",
    envKey: "STEPFUN_API_KEY",
    envModel: "STEPFUN_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.stepfun.com/v1",
    defaultModel: "step-2-16k",
    websiteUrl: "https://platform.stepfun.com",
    category: "china",
    isOfficial: true,
  },
  {
    id: "minimaxi",
    name: "MiniMax",
    envKey: "MINIMAX_API_KEY",
    envModel: "MINIMAX_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.minimaxi.com/v1",
    defaultModel: "MiniMax-Text-01",
    websiteUrl: "https://platform.minimaxi.com",
    category: "china",
    isOfficial: true,
  },
  {
    id: "longcat",
    name: "Meituan LongCat",
    envKey: "LONGCAT_API_KEY",
    envModel: "LONGCAT_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.longcat.chat/openai/v1",
    defaultModel: "LongCat-Flash-Chat",
    websiteUrl: "https://longcat.chat/platform",
    apiKeyUrl: "https://longcat.chat/platform/api_keys",
    category: "china",
    isOfficial: true,
  },
  {
    id: "bailing",
    name: "Ant Ling (蚂蚁 Ling)",
    envKey: "BAILING_API_KEY",
    envModel: "BAILING_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.tbox.cn/api/llm/v1",
    defaultModel: "Ling-2.5-1T",
    websiteUrl: "https://alipaytbox.yuque.com/sxs0ba/ling/get_started",
    category: "china",
    isOfficial: true,
  },
  {
    id: "xiaomi-mimo",
    name: "Xiaomi MiMo",
    envKey: "MIMO_API_KEY",
    envModel: "MIMO_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.xiaomimimo.com/v1",
    defaultModel: "mimo-v2.5-pro",
    websiteUrl: "https://platform.xiaomimimo.com",
    apiKeyUrl: "https://platform.xiaomimimo.com/#/console/api-keys",
    category: "china",
    isOfficial: true,
  },
  {
    id: "modelscope",
    name: "Alibaba ModelScope (魔搭)",
    envKey: "MODELSCOPE_API_KEY",
    envModel: "MODELSCOPE_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api-inference.modelscope.cn/v1",
    defaultModel: "ZhipuAI/GLM-4-Plus",
    websiteUrl: "https://modelscope.cn",
    apiKeyUrl: "https://modelscope.cn/my/myaccesstoken",
    category: "china",
  },
  {
    id: "volcengine-coding",
    name: "Volcano Coding Plan (火山 Agentplan)",
    envKey: "VOLC_CODING_API_KEY",
    envModel: "VOLC_CODING_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://ark.cn-beijing.volces.com/api/coding/v3",
    defaultModel: "ark-code-latest",
    websiteUrl: "https://www.volcengine.com/activity/codingplan",
    category: "china",
    isPartner: true,
  },
  {
    id: "kat-coder",
    name: "StreamLake KAT-Coder",
    envKey: "KAT_API_KEY",
    envModel: "KAT_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://vanchin.streamlake.ai/api/gateway/v1/endpoints",
    defaultModel: "kat-coder",
    websiteUrl: "https://console.streamlake.ai",
    apiKeyUrl: "https://console.streamlake.ai/console/api-key",
    category: "china",
  },

  // ──────────────── international (non-Chinese 1P vendors) ────────────────
  {
    id: "mistral",
    name: "Mistral AI",
    envKey: "MISTRAL_API_KEY",
    envModel: "MISTRAL_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.mistral.ai/v1",
    defaultModel: "mistral-large-latest",
    websiteUrl: "https://mistral.ai",
    apiKeyUrl: "https://console.mistral.ai/api-keys",
    category: "international",
    isOfficial: true,
  },
  {
    id: "cohere",
    name: "Cohere",
    envKey: "COHERE_API_KEY",
    envModel: "COHERE_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.cohere.ai/v1",
    defaultModel: "command-r-plus",
    websiteUrl: "https://cohere.com",
    apiKeyUrl: "https://dashboard.cohere.com/api-keys",
    category: "international",
    isOfficial: true,
  },
  {
    id: "groq",
    name: "Groq",
    envKey: "GROQ_API_KEY",
    envModel: "GROQ_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.groq.com/openai/v1",
    defaultModel: "llama-3.3-70b-versatile",
    websiteUrl: "https://groq.com",
    apiKeyUrl: "https://console.groq.com/keys",
    category: "international",
    isOfficial: true,
  },
  {
    id: "xai",
    name: "xAI Grok",
    envKey: "XAI_API_KEY",
    envModel: "XAI_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.x.ai/v1",
    defaultModel: "grok-2-latest",
    websiteUrl: "https://x.ai",
    apiKeyUrl: "https://console.x.ai",
    category: "international",
    isOfficial: true,
  },
  {
    id: "perplexity",
    name: "Perplexity",
    envKey: "PERPLEXITY_API_KEY",
    envModel: "PERPLEXITY_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.perplexity.ai",
    defaultModel: "sonar-pro",
    websiteUrl: "https://perplexity.ai",
    apiKeyUrl: "https://www.perplexity.ai/settings/api",
    category: "international",
    isOfficial: true,
  },
  {
    id: "together",
    name: "Together AI",
    envKey: "TOGETHER_API_KEY",
    envModel: "TOGETHER_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.together.xyz/v1",
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    websiteUrl: "https://together.ai",
    apiKeyUrl: "https://api.together.ai/settings/api-keys",
    category: "international",
    isOfficial: true,
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    envKey: "FIREWORKS_API_KEY",
    envModel: "FIREWORKS_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    defaultModel: "accounts/fireworks/models/llama-v3p3-70b-instruct",
    websiteUrl: "https://fireworks.ai",
    apiKeyUrl: "https://fireworks.ai/account/api-keys",
    category: "international",
    isOfficial: true,
  },
  {
    id: "nous-research",
    name: "Nous Research",
    envKey: "NOUS_API_KEY",
    envModel: "NOUS_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://inference-api.nousresearch.com/v1",
    defaultModel: "Hermes-4-405B",
    websiteUrl: "https://nousresearch.com",
    apiKeyUrl: "https://portal.nousresearch.com/",
    category: "international",
    isOfficial: true,
  },

  // ──────────────── aggregator (routing services) ────────────────
  {
    id: "openrouter",
    name: "OpenRouter",
    envKey: "OPENROUTER_API_KEY",
    envModel: "OPENROUTER_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://openrouter.ai/api/v1",
    defaultModel: "anthropic/claude-3.5-sonnet",
    websiteUrl: "https://openrouter.ai",
    apiKeyUrl: "https://openrouter.ai/keys",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "therouter",
    name: "TheRouter",
    envKey: "THEROUTER_API_KEY",
    envModel: "THEROUTER_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.therouter.ai/v1",
    defaultModel: "anthropic/claude-3.5-sonnet",
    websiteUrl: "https://therouter.ai",
    apiKeyUrl: "https://dashboard.therouter.ai",
    category: "aggregator",
  },
  {
    id: "novita",
    name: "Novita AI",
    envKey: "NOVITA_API_KEY",
    envModel: "NOVITA_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.novita.ai/openai/v1",
    defaultModel: "meta-llama/llama-3.3-70b-instruct",
    websiteUrl: "https://novita.ai",
    category: "aggregator",
  },
  {
    id: "nvidia-nim",
    name: "NVIDIA NIM",
    envKey: "NVIDIA_API_KEY",
    envModel: "NVIDIA_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    defaultModel: "meta/llama-3.3-70b-instruct",
    websiteUrl: "https://build.nvidia.com",
    apiKeyUrl: "https://build.nvidia.com/settings/api-keys",
    category: "aggregator",
    isOfficial: true,
  },
  {
    id: "siliconflow",
    name: "SiliconFlow (硅基流动)",
    envKey: "SILICONFLOW_API_KEY",
    envModel: "SILICONFLOW_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.siliconflow.cn/v1",
    defaultModel: "Qwen/Qwen2.5-72B-Instruct",
    websiteUrl: "https://siliconflow.cn",
    apiKeyUrl: "https://cloud.siliconflow.cn/account/ak",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "shengsuanyun",
    name: "Shengsuanyun (胜算云)",
    envKey: "SHENGSUAN_API_KEY",
    envModel: "SHENGSUAN_MODEL",
    apiFormat: "anthropic",
    baseUrl: "https://router.shengsuanyun.com/api",
    endpointCandidates: [
      "https://router.shengsuanyun.com/api",
      "https://router.shengsuanyun.com/api/v1",
    ],
    defaultModel: "claude-3-5-sonnet-latest",
    websiteUrl: "https://www.shengsuanyun.com",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "patewayai",
    name: "PatewayAI",
    envKey: "PATHWAY_API_KEY",
    envModel: "PATHWAY_MODEL",
    apiFormat: "anthropic",
    baseUrl: "https://api.pateway.ai",
    defaultModel: "claude-3-5-sonnet-latest",
    websiteUrl: "https://pateway.ai",
    category: "aggregator",
  },
  {
    id: "ccsub",
    name: "CCSub",
    envKey: "CCSUB_API_KEY",
    envModel: "CCSUB_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://www.ccsub.net/v1",
    defaultModel: "gpt-4o",
    websiteUrl: "https://www.ccsub.net",
    category: "aggregator",
  },
  {
    id: "unity2",
    name: "Unity2.ai",
    envKey: "UNITY2_API_KEY",
    envModel: "UNITY2_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.unity2.ai/v1",
    defaultModel: "gpt-4o",
    websiteUrl: "https://unity2.ai",
    apiKeyUrl: "https://unity2.ai/register?source=maximilian",
    category: "aggregator",
  },
  {
    id: "aihubmix",
    name: "AiHubMix",
    envKey: "AIHUBMIX_API_KEY",
    envModel: "AIHUBMIX_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://aihubmix.com/v1",
    defaultModel: "gpt-4o",
    websiteUrl: "https://aihubmix.com",
    category: "aggregator",
  },
  {
    id: "cherryin",
    name: "CherryIN",
    envKey: "CHERRYIN_API_KEY",
    envModel: "CHERRYIN_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://open.cherryin.net/v1",
    defaultModel: "gpt-4o",
    websiteUrl: "https://open.cherryin.ai",
    apiKeyUrl: "https://open.cherryin.ai/console/token",
    category: "aggregator",
  },
  {
    id: "dmxapi",
    name: "DMXAPI",
    envKey: "DMXAPI_API_KEY",
    envModel: "DMXAPI_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://www.dmxapi.cn/v1",
    defaultModel: "gpt-4o",
    websiteUrl: "https://www.dmxapi.cn",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "packycode",
    name: "PackyCode",
    envKey: "PACKYCODE_API_KEY",
    envModel: "PACKYCODE_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://www.packyapi.com/v1",
    endpointCandidates: [
      "https://www.packyapi.com/v1",
      "https://api-slb.packyapi.com/v1",
    ],
    defaultModel: "claude-3-5-sonnet-latest",
    websiteUrl: "https://www.packyapi.com",
    apiKeyUrl: "https://www.packyapi.com/register?aff=maximilian",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "apikey-fun",
    name: "APIKEY.FUN",
    envKey: "APIKEYFUN_API_KEY",
    envModel: "APIKEYFUN_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.apikey.fun/v1",
    endpointCandidates: [
      "https://api.apikey.fun/v1",
      "https://slb.apikey.fun/v1",
    ],
    defaultModel: "gpt-4o",
    websiteUrl: "https://apikey.fun",
    apiKeyUrl: "https://apikey.fun/register?aff=MAXIMILIAN",
    category: "aggregator",
  },
  {
    id: "apinebula",
    name: "APINebula",
    envKey: "APINEBULA_API_KEY",
    envModel: "APINEBULA_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://apinebula.com/v1",
    defaultModel: "gpt-4o",
    websiteUrl: "https://apinebula.com",
    category: "aggregator",
  },
  {
    id: "atlascloud",
    name: "AtlasCloud",
    envKey: "ATLASCLOUD_API_KEY",
    envModel: "ATLASCLOUD_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.atlascloud.ai/v1",
    defaultModel: "claude-3-5-sonnet-latest",
    websiteUrl: "https://www.atlascloud.ai/console/coding-plan",
    category: "aggregator",
  },
  {
    id: "sudocode",
    name: "SudoCode",
    envKey: "SUDOCODE_API_KEY",
    envModel: "SUDOCODE_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://sudocode.us/v1",
    endpointCandidates: ["https://sudocode.us/v1", "https://sudocode.run/v1"],
    defaultModel: "gpt-4o",
    websiteUrl: "https://sudocode.us",
    category: "aggregator",
  },
  {
    id: "cubence",
    name: "Cubence",
    envKey: "CUBENCE_API_KEY",
    envModel: "CUBENCE_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.cubence.com/v1",
    endpointCandidates: [
      "https://api.cubence.com/v1",
      "https://api-cf.cubence.com/v1",
      "https://api-dmit.cubence.com/v1",
      "https://api-bwg.cubence.com/v1",
    ],
    defaultModel: "claude-3-5-sonnet-latest",
    websiteUrl: "https://cubence.com",
    apiKeyUrl: "https://cubence.com/signup?code=MAXIMILIAN",
    category: "aggregator",
  },
  {
    id: "aigocode",
    name: "AIGoCode",
    envKey: "AIGOCODE_API_KEY",
    envModel: "AIGOCODE_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.aigocode.com/v1",
    defaultModel: "claude-3-5-sonnet-latest",
    websiteUrl: "https://aigocode.com",
    apiKeyUrl: "https://aigocode.com/invite/MAX",
    category: "aggregator",
  },
  {
    id: "rightcode",
    name: "RightCode",
    envKey: "RIGHTCODE_API_KEY",
    envModel: "RIGHTCODE_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://www.right.codes/v1",
    defaultModel: "claude-3-5-sonnet-latest",
    websiteUrl: "https://www.right.codes",
    apiKeyUrl: "https://www.right.codes/register?aff=MAXIMILIAN",
    category: "aggregator",
  },
  {
    id: "aicodemirror",
    name: "AICodeMirror",
    envKey: "AICODEMIRROR_API_KEY",
    envModel: "AICODEMIRROR_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.aicodemirror.com/v1",
    endpointCandidates: [
      "https://api.aicodemirror.com/v1",
      "https://api.claudecode.net.cn/v1",
    ],
    defaultModel: "claude-3-5-sonnet-latest",
    websiteUrl: "https://www.aicodemirror.com",
    apiKeyUrl: "https://www.aicodemirror.com/register?invitecode=MAXIMILIAN",
    category: "aggregator",
  },
  {
    id: "crazyrouter",
    name: "CrazyRouter",
    envKey: "CRAZYROUTER_API_KEY",
    envModel: "CRAZYROUTER_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://cn.crazyrouter.com/v1",
    defaultModel: "gpt-4o",
    websiteUrl: "https://www.crazyrouter.com",
    apiKeyUrl: "https://www.crazyrouter.com/register?aff=maximilian",
    category: "aggregator",
  },
  {
    id: "sssaicode",
    name: "SSSAiCode",
    envKey: "SSSAI_API_KEY",
    envModel: "SSSAI_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://node-hk.sssaicodeapi.com/api/v1",
    endpointCandidates: [
      "https://node-hk.sssaicodeapi.com/api/v1",
      "https://node-hk.sssaiapi.com/api/v1",
      "https://node-cf.sssaicodeapi.com/api/v1",
    ],
    defaultModel: "claude-3-5-sonnet-latest",
    websiteUrl: "https://sssaicodeapi.com",
    apiKeyUrl: "https://sssaicodeapi.com/register?ref=MAXIMILIAN",
    category: "aggregator",
  },
  {
    id: "compshare",
    name: "Compshare (ModelVerse)",
    envKey: "COMPSHARE_API_KEY",
    envModel: "COMPSHARE_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.modelverse.cn/v1",
    endpointCandidates: ["https://api.modelverse.cn/v1", "https://cp.compshare.cn/v1"],
    defaultModel: "claude-3-5-sonnet-latest",
    websiteUrl: "https://www.compshare.cn",
    apiKeyUrl: "https://www.compshare.cn/coding-plan?ytag=GPU_YY_YX_git_maximilian",
    category: "aggregator",
  },
  {
    id: "micu",
    name: "Micu",
    envKey: "MICU_API_KEY",
    envModel: "MICU_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://www.micuapi.ai/v1",
    defaultModel: "gpt-4o",
    websiteUrl: "https://www.micuapi.ai",
    apiKeyUrl: "https://www.micuapi.ai/register?aff=MAX",
    category: "aggregator",
  },
  {
    id: "ctok",
    name: "CTok.ai",
    envKey: "CTOK_API_KEY",
    envModel: "CTOK_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://api.ctok.ai/v1",
    defaultModel: "gpt-4o",
    websiteUrl: "https://ctok.ai",
    category: "aggregator",
  },
  {
    id: "e-flowcode",
    name: "E-FlowCode",
    envKey: "EFLOW_API_KEY",
    envModel: "EFLOW_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://e-flowcode.cc/v1",
    defaultModel: "gpt-4o",
    websiteUrl: "https://e-flowcode.cc",
    category: "aggregator",
  },
  {
    id: "claudeapi",
    name: "ClaudeAPI (聚合)",
    envKey: "CLAUDEAPI_API_KEY",
    envModel: "CLAUDEAPI_MODEL",
    apiFormat: "anthropic",
    baseUrl: "https://gw.claudeapi.com",
    defaultModel: "claude-3-5-sonnet-latest",
    websiteUrl: "https://claudeapi.com",
    apiKeyUrl: "https://console.claudeapi.com/register?aff=MAX",
    category: "aggregator",
  },
  {
    id: "claudecn",
    name: "ClaudeCN",
    envKey: "CLAUDECN_API_KEY",
    envModel: "CLAUDECN_MODEL",
    apiFormat: "anthropic",
    baseUrl: "https://claudecn.top",
    defaultModel: "claude-3-5-sonnet-latest",
    websiteUrl: "https://claudecn.top",
    apiKeyUrl: "https://claudecn.top/register?aff=maximilian",
    category: "aggregator",
  },
  {
    id: "relaxycode",
    name: "RelaxyCode",
    envKey: "RELAXY_API_KEY",
    envModel: "RELAXY_MODEL",
    apiFormat: "anthropic",
    baseUrl: "https://www.relaxycode.com",
    defaultModel: "claude-3-5-sonnet-latest",
    websiteUrl: "https://www.relaxycode.com",
    category: "aggregator",
  },
  {
    id: "runapi",
    name: "RunAPI",
    envKey: "RUNAPI_API_KEY",
    envModel: "RUNAPI_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://runapi.co",
    defaultModel: "gpt-4o",
    websiteUrl: "https://runapi.co",
    category: "aggregator",
  },
  {
    id: "pipellm",
    name: "PIPELLM",
    envKey: "PIPELLM_API_KEY",
    envModel: "PIPELLM_MODEL",
    apiFormat: "anthropic",
    baseUrl: "https://cc-api.pipellm.ai",
    defaultModel: "claude-3-5-sonnet-latest",
    websiteUrl: "https://code.pipellm.ai",
    apiKeyUrl: "https://code.pipellm.ai/login?ref=maximilian",
    category: "aggregator",
  },

  // ──────────────── cloud (cloud-hosted proxies) ────────────────
  {
    id: "aws-bedrock",
    name: "AWS Bedrock",
    envKey: "AWS_BEDROCK_API_KEY",
    envModel: "AWS_BEDROCK_MODEL",
    apiFormat: "anthropic",
    baseUrl: "https://bedrock-runtime.us-west-2.amazonaws.com",
    defaultModel: "anthropic.claude-3-5-sonnet-20241022-v2:0",
    websiteUrl: "https://aws.amazon.com/bedrock/",
    category: "cloud",
    cloudProvider: "aws",
    hidden: true,
  },
  {
    id: "azure-openai",
    name: "Azure OpenAI",
    envKey: "AZURE_OPENAI_API_KEY",
    envModel: "AZURE_OPENAI_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "https://YOUR_RESOURCE_NAME.openai.azure.com/openai",
    defaultModel: "gpt-4o",
    websiteUrl: "https://learn.microsoft.com/azure/ai-services/openai",
    category: "cloud",
    cloudProvider: "azure",
    hidden: true,
  },

  // ──────────────── hidden (OAuth / not-yet-implemented) ────────────────
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    envKey: "GITHUB_COPILOT_TOKEN",
    apiFormat: "openai_chat",
    baseUrl: "https://api.githubcopilot.com",
    defaultModel: "gpt-4o",
    websiteUrl: "https://github.com/features/copilot",
    category: "aggregator",
    requiresOAuth: true,
    hidden: true,
  },
  {
    id: "codex",
    name: "OpenAI Codex (ChatGPT Plus/Pro)",
    envKey: "CODEX_OAUTH_TOKEN",
    apiFormat: "openai_responses",
    baseUrl: "https://chatgpt.com/backend-api/codex",
    defaultModel: "gpt-5",
    websiteUrl: "https://openai.com/chatgpt/pricing",
    category: "official",
    requiresOAuth: true,
    hidden: true,
  },

  // ──────────────── local (self-hosted inference) ────────────────
  {
    id: "ollama",
    name: "Ollama (local)",
    envKey: "OLLAMA_ENABLED",
    envModel: "OLLAMA_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "http://localhost:11434/v1",
    defaultModel: "llama3.2",
    websiteUrl: "https://ollama.com",
    category: "custom",
  },
  {
    id: "lmstudio",
    name: "LM Studio (local)",
    envKey: "LMSTUDIO_ENABLED",
    envModel: "LMSTUDIO_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "http://localhost:1234/v1",
    defaultModel: "qwen2.5-7b-instruct",
    websiteUrl: "https://lmstudio.ai",
    category: "custom",
  },
  {
    id: "vllm",
    name: "vLLM (local)",
    envKey: "VLLM_ENABLED",
    envModel: "VLLM_MODEL",
    apiFormat: "openai_chat",
    baseUrl: "http://localhost:8000/v1",
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct",
    websiteUrl: "https://docs.vllm.ai",
    category: "custom",
  },
]

/**
 * Build a stable lookup map: id → preset.
 * O(N) once at module load.
 */
export const PROVIDER_PRESETS_BY_ID: ReadonlyMap<string, ProviderPreset> = new Map(
  PROVIDER_PRESETS.map((p) => [p.id, p])
)

/**
 * Visible presets (excluding hidden OAuth / cloud placeholders).
 */
export const VISIBLE_PROVIDER_PRESETS: ProviderPreset[] = PROVIDER_PRESETS.filter(
  (p) => !p.hidden
)