/**
 * Provider presets — full CC Switch preset database.
 *
 * Borrowed wholesale from CC Switch (https://github.com/farion1231/cc-switch).
 * 350 raw entries across 8 source files. After filtering out marketing / docs
 * URLs and placeholders, and deduping on (slug + baseUrl + apiFormat), the
 * curated list below preserves every distinct endpoint variant of the same
 * LLM provider — many Chinese routers expose parallel Anthropic-compatible,
 * OpenAI-compatible, and Gemini-compatible endpoints, and users legitimately
 * want all of them available.
 *
 * API keys live ONLY in env vars; this file holds static metadata only.
 *
 * Categories:
 *   - official        first-party LLM vendor (Anthropic, OpenAI, Google)
 *   - international   non-Chinese 1P vendor (Mistral, Cohere, Groq, ...)
 *   - china           Chinese 1P vendor (DeepSeek, Zhipu, Moonshot, ...)
 *   - aggregator      routing service (OpenRouter, PackyCode, ...)
 *   - cloud           cloud-hosted proxy (AWS Bedrock, Azure OpenAI)
 *   - custom          local inference (Ollama, LM Studio)
 *
 * OAuth-only presets are hidden at runtime; they appear in the source so
 * future work can wire them up.
 */

import type { ProviderPreset } from "./types.js"

/* eslint-disable comma-dangle */

export const PROVIDER_PRESETS: ProviderPreset[] = [
  // ──────────────── official (first-party LLM vendors) ────────────────
  {
    id: "anthropic",
    name: "Anthropic",
    envKey: "ANTHROPIC_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.anthropic.com",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "official",
    isOfficial: true,
  },
  {
    id: "google",
    name: "Google",
    envKey: "GOOGLE_API_KEY",
    apiFormat: "gemini_native",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    defaultModel: "gemini-2.5-flash",
    category: "official",
    isOfficial: true,
  },
  {
    id: "nous-research",
    name: "Nous Research",
    envKey: "NOUS_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://inference-api.nousresearch.com/v1",
    defaultModel: "gpt-4o",
    category: "official",
    isOfficial: true,
  },
  {
    id: "openai",
    name: "OpenAI",
    envKey: "OPENAI_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.openai.com/v1",
    defaultModel: "gpt-4o",
    category: "official",
    isOfficial: true,
  },
  // ──────────────── china (Chinese 1P vendors) ────────────────
  {
    id: "agentplan",
    name: "火山Agentplan",
    envKey: "AGENTPLAN_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://ark.cn-beijing.volces.com/api/coding",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "china",
    isPartner: true,
  },
  {
    id: "agentplan-2",
    name: "火山Agentplan",
    envKey: "AGENTPLAN_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://ark.cn-beijing.volces.com/api/coding/v3",
    defaultModel: "gpt-4o",
    category: "china",
    isPartner: true,
  },
  {
    id: "agentplan-coding",
    name: "火山Agentplan",
    envKey: "AGENTPLAN_CODING_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://ark.cn-beijing.volces.com/api/coding",
    defaultModel: "gpt-4o",
    category: "china",
    isPartner: true,
  },
  {
    id: "baidu-qianfan",
    name: "Baidu Qianfan Coding Plan",
    envKey: "QIANFAN_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://qianfan.baidubce.com/anthropic/coding",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "china",
  },
  {
    id: "bailing",
    name: "BaiLing",
    envKey: "BAILING_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.tbox.cn/api/anthropic",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "china",
  },
  {
    id: "bailing-2",
    name: "BaiLing",
    envKey: "BAILING_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.tbox.cn/v1",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "bailing-anthropic",
    name: "BaiLing",
    envKey: "BAILING_ANTHROPIC_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.tbox.cn/api/anthropic",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "dashscope-bailian",
    name: "Bailian",
    envKey: "DASHSCOPE_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://dashscope.aliyuncs.com/apps/anthropic",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "china",
  },
  {
    id: "dashscope-bailian-2",
    name: "Bailian",
    envKey: "DASHSCOPE_BAILIAN_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "dashscope-coding",
    name: "Bailian For Coding",
    envKey: "DASHSCOPE_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://coding.dashscope.aliyuncs.com/apps/anthropic",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "china",
  },
  {
    id: "dashscope-coding-2",
    name: "Bailian For Coding",
    envKey: "DASHSCOPE_CODING_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://coding.dashscope.aliyuncs.com/apps/anthropic",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    envKey: "DEEPSEEK_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.deepseek.com/anthropic",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "china",
  },
  {
    id: "deepseek-2",
    name: "DeepSeek",
    envKey: "DEEPSEEK_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.deepseek.com/v1",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "deepseek-openai",
    name: "DeepSeek",
    envKey: "DEEPSEEK_OPENAI_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.deepseek.com",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "doubao",
    name: "DouBaoSeed",
    envKey: "DOUBAO_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://ark.cn-beijing.volces.com/api/compatible",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "china",
    isPartner: true,
  },
  {
    id: "doubao-2",
    name: "DouBaoSeed",
    envKey: "DOUBAO_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    defaultModel: "gpt-4o",
    category: "china",
    isPartner: true,
  },
  {
    id: "doubao-compatible",
    name: "DouBaoSeed",
    envKey: "DOUBAO_COMPATIBLE_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://ark.cn-beijing.volces.com/api/compatible",
    defaultModel: "gpt-4o",
    category: "china",
    isPartner: true,
  },
  {
    id: "kimi",
    name: "Kimi",
    envKey: "MOONSHOT_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.moonshot.cn/anthropic",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "china",
  },
  {
    id: "kimi-2",
    name: "Kimi",
    envKey: "KIMI_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.moonshot.cn/v1",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "kimi-coding",
    name: "Kimi For Coding",
    envKey: "MOONSHOT_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.kimi.com/coding/",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "china",
  },
  {
    id: "kimi-coding-2",
    name: "Kimi For Coding",
    envKey: "KIMI_CODING_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.kimi.com/coding/v1",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "kimi-coding-coding",
    name: "Kimi For Coding",
    envKey: "KIMI_CODING_CODING_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.kimi.com/coding/",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "kimi-coding-v",
    name: "Kimi For Coding",
    envKey: "KIMI_CODING_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.kimi.com/v1",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "kimi-k2-7-code",
    name: "Kimi K2.7 Code",
    envKey: "KIMI_K2_7_CODE_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.moonshot.cn/v1",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "longcat",
    name: "Longcat",
    envKey: "LONGCAT_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.longcat.chat/anthropic",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "china",
  },
  {
    id: "longcat-2",
    name: "Longcat",
    envKey: "LONGCAT_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.longcat.chat/v1",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "longcat-v",
    name: "Longcat",
    envKey: "LONGCAT_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.longcat.chat/openai/v1",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "minimaxi",
    name: "MiniMax",
    envKey: "MINIMAX_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.minimaxi.com/anthropic",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "china",
  },
  {
    id: "minimaxi-2",
    name: "MiniMax",
    envKey: "MINIMAXI_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://platform.minimaxi.com",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "minimaxi-v",
    name: "MiniMax",
    envKey: "MINIMAXI_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.minimaxi.com/v1",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "modelscope",
    name: "ModelScope",
    envKey: "MODELSCOPE_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api-inference.modelscope.cn",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "china",
  },
  {
    id: "modelscope-2",
    name: "ModelScope",
    envKey: "MODELSCOPE_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://modelscope.cn",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "modelscope-v",
    name: "ModelScope",
    envKey: "MODELSCOPE_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api-inference.modelscope.cn/v1",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "qwen-coder",
    name: "Qwen Coder",
    envKey: "QWEN_CODER_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "stepfun",
    name: "StepFun",
    envKey: "STEPFUN_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.stepfun.com/step_plan",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "china",
  },
  {
    id: "stepfun-2",
    name: "StepFun",
    envKey: "STEPFUN_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.stepfun.com/step_plan/v1",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "stepfun-alt",
    name: "StepFun en",
    envKey: "STEPFUN_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.stepfun.ai/step_plan",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "china",
  },
  {
    id: "stepfun-alt-2",
    name: "StepFun en",
    envKey: "STEPFUN_ALT_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.stepfun.ai/step_plan/v1",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "stepfun-step-plan",
    name: "StepFun Step Plan",
    envKey: "STEPFUN_STEP_PLAN_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.stepfun.com/step_plan/v1",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "stepfun-v",
    name: "StepFun",
    envKey: "STEPFUN_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.stepfun.ai/v1",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "xiaomi-mimo",
    name: "Xiaomi MiMo",
    envKey: "MIMO_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.xiaomimimo.com/anthropic",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "china",
  },
  {
    id: "xiaomi-mimo-2",
    name: "Xiaomi MiMo",
    envKey: "XIAOMI_MIMO_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.xiaomimimo.com/v1",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "xiaomi-mimo-cn",
    name: "Xiaomi MiMo Token Plan (China)",
    envKey: "MIMO_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://token-plan-cn.xiaomimimo.com/anthropic",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "china",
  },
  {
    id: "xiaomi-mimo-cn-2",
    name: "Xiaomi MiMo Token Plan (China)",
    envKey: "XIAOMI_MIMO_CN_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://token-plan-cn.xiaomimimo.com/v1",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "zhipu",
    name: "Zhipu GLM",
    envKey: "ZHIPU_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://open.bigmodel.cn/api/anthropic",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "china",
  },
  {
    id: "zhipu-2",
    name: "Zhipu GLM",
    envKey: "ZHIPU_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://open.bigmodel.cn",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "zhipu-en",
    name: "Zhipu GLM en",
    envKey: "ZHIPU_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.z.ai/api/anthropic",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "china",
  },
  {
    id: "zhipu-en-2",
    name: "Zhipu GLM en",
    envKey: "ZHIPU_EN_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://z.ai",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "zhipu-en-v",
    name: "Zhipu GLM en",
    envKey: "ZHIPU_EN_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.z.ai/api/coding/paas/v4",
    defaultModel: "gpt-4o",
    category: "china",
  },
  {
    id: "zhipu-v",
    name: "Zhipu GLM",
    envKey: "ZHIPU_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://open.bigmodel.cn/api/coding/paas/v4",
    defaultModel: "gpt-4o",
    category: "china",
  },
  // ──────────────── aggregator (routing services) ────────────────
  {
    id: "aicodemirror",
    name: "AICodeMirror",
    envKey: "AICODEMIRROR_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.aicodemirror.com/api/claudecode",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "aicodemirror-2",
    name: "AICodeMirror",
    envKey: "AICODEMIRROR_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://www.aicodemirror.com",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "aicodemirror-3",
    name: "AICodeMirror",
    envKey: "AICODEMIRROR_3_API_KEY",
    apiFormat: "gemini_native",
    baseUrl: "https://api.aicodemirror.com/api/gemini",
    defaultModel: "gemini-2.5-flash",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "aicodemirror-claudecode",
    name: "AICodeMirror",
    envKey: "AICODEMIRROR_CLAUDECODE_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.aicodemirror.com/api/claudecode",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "aigocode",
    name: "AIGoCode",
    envKey: "AIGOCODE_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.aigocode.com",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "aigocode-2",
    name: "AIGoCode",
    envKey: "AIGOCODE_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://aigocode.com",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "aigocode-3",
    name: "AIGoCode",
    envKey: "AIGOCODE_3_API_KEY",
    apiFormat: "gemini_native",
    baseUrl: "https://api.aigocode.com",
    defaultModel: "gemini-2.5-flash",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "aigocode-openai",
    name: "AIGoCode",
    envKey: "AIGOCODE_OPENAI_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.aigocode.com",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "aihubmix",
    name: "AiHubMix",
    envKey: "AIHUBMIX_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://aihubmix.com",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
  },
  {
    id: "aihubmix-2",
    name: "AiHubMix",
    envKey: "AIHUBMIX_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://aihubmix.com",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "aihubmix-v",
    name: "AiHubMix",
    envKey: "AIHUBMIX_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://aihubmix.com/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "apikey-fun",
    name: "APIKEY.FUN",
    envKey: "APIKEYFUN_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.apikey.fun",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "apikey-fun-2",
    name: "APIKEY.FUN",
    envKey: "APIKEY_FUN_2_API_KEY",
    apiFormat: "openai_responses",
    baseUrl: "https://apikey.fun",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "apikey-fun-3",
    name: "APIKEY.FUN",
    envKey: "APIKEY_FUN_3_API_KEY",
    apiFormat: "gemini_native",
    baseUrl: "https://api.apikey.fun",
    defaultModel: "gemini-2.5-flash",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "apikey-fun-4",
    name: "APIKEY.FUN",
    envKey: "APIKEY_FUN_4_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.apikey.fun/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "apikey-fun-openai",
    name: "APIKEY.FUN",
    envKey: "APIKEY_FUN_OPENAI_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.apikey.fun",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "apinebula",
    name: "APINebula",
    envKey: "APINEBULA_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://apinebula.com",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "apinebula-2",
    name: "APINebula",
    envKey: "APINEBULA_2_API_KEY",
    apiFormat: "openai_responses",
    baseUrl: "https://apinebula.com",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "apinebula-3",
    name: "APINebula",
    envKey: "APINEBULA_3_API_KEY",
    apiFormat: "gemini_native",
    baseUrl: "https://apinebula.com",
    defaultModel: "gemini-2.5-flash",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "apinebula-4",
    name: "APINebula",
    envKey: "APINEBULA_4_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://apinebula.com/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "atlascloud",
    name: "AtlasCloud",
    envKey: "ATLASCLOUD_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.atlascloud.ai",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "atlascloud-2",
    name: "AtlasCloud",
    envKey: "ATLASCLOUD_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://www.atlascloud.ai/console/coding-plan",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "atlascloud-v",
    name: "AtlasCloud",
    envKey: "ATLASCLOUD_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.atlascloud.ai/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "byteplus",
    name: "BytePlus",
    envKey: "BYTEPLUS_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://ark.ap-southeast.bytepluses.com/api/coding",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "byteplus-2",
    name: "BytePlus",
    envKey: "BYTEPLUS_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://ark.ap-southeast.bytepluses.com/api/coding/v3",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "byteplus-coding",
    name: "BytePlus",
    envKey: "BYTEPLUS_CODING_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://ark.ap-southeast.bytepluses.com/api/coding",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "ccsub",
    name: "CCSub",
    envKey: "CCSUB_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://www.ccsub.net",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "ccsub-2",
    name: "CCSub",
    envKey: "CCSUB_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://www.ccsub.net",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "ccsub-v",
    name: "CCSub",
    envKey: "CCSUB_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://www.ccsub.net/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "cherryin",
    name: "CherryIN",
    envKey: "CHERRYIN_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://open.cherryin.net",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
  },
  {
    id: "cherryin-2",
    name: "CherryIN",
    envKey: "CHERRYIN_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://open.cherryin.ai",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "cherryin-3",
    name: "CherryIN",
    envKey: "CHERRYIN_3_API_KEY",
    apiFormat: "gemini_native",
    baseUrl: "https://open.cherryin.net",
    defaultModel: "gemini-2.5-flash",
    category: "aggregator",
  },
  {
    id: "cherryin-openai",
    name: "CherryIN",
    envKey: "CHERRYIN_OPENAI_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://open.cherryin.net",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "cherryin-v",
    name: "CherryIN",
    envKey: "CHERRYIN_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://open.cherryin.net/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "claude-desktop-official",
    name: "Claude Desktop Official",
    envKey: "CLAUDE_DESKTOP_OFFICIAL_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://claude.ai/download",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
  },
  {
    id: "claudeapi",
    name: "ClaudeAPI",
    envKey: "CLAUDEAPI_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://gw.claudeapi.com",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "claudecn",
    name: "ClaudeCN",
    envKey: "CLAUDECN_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://claudecn.top",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "claudecn-2",
    name: "ClaudeCN",
    envKey: "CLAUDECN_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://claudecn.top",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "codex",
    name: "Codex",
    envKey: "CODEX_OAUTH_TOKEN",
    apiFormat: "openai_responses",
    baseUrl: "https://chatgpt.com/backend-api/codex",
    defaultModel: "gpt-4o",
    category: "aggregator",
    hidden: true,
    requiresOAuth: true,
  },
  {
    id: "compshare",
    name: "Compshare",
    envKey: "COMPSHARE_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.modelverse.cn",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "compshare-2",
    name: "Compshare",
    envKey: "COMPSHARE_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://www.compshare.cn",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "compshare-coding-plan",
    name: "Compshare Coding Plan",
    envKey: "COMPSHARE_CODING_PLAN_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://cp.compshare.cn",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "compshare-coding-plan-2",
    name: "Compshare Coding Plan",
    envKey: "COMPSHARE_CODING_PLAN_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://www.compshare.cn",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "compshare-coding-plan-v",
    name: "Compshare Coding Plan",
    envKey: "COMPSHARE_CODING_PLAN_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://cp.compshare.cn/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "compshare-v",
    name: "Compshare",
    envKey: "COMPSHARE_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.modelverse.cn/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "crazyrouter",
    name: "CrazyRouter",
    envKey: "CRAZYROUTER_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://cn.crazyrouter.com",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "crazyrouter-2",
    name: "CrazyRouter",
    envKey: "CRAZYROUTER_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://www.crazyrouter.com",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "crazyrouter-3",
    name: "CrazyRouter",
    envKey: "CRAZYROUTER_3_API_KEY",
    apiFormat: "gemini_native",
    baseUrl: "https://cn.crazyrouter.com",
    defaultModel: "gemini-2.5-flash",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "crazyrouter-openai",
    name: "CrazyRouter",
    envKey: "CRAZYROUTER_OPENAI_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://cn.crazyrouter.com",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "crazyrouter-v",
    name: "CrazyRouter",
    envKey: "CRAZYROUTER_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://cn.crazyrouter.com/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "ctok-ai",
    name: "CTok.ai",
    envKey: "CTOK_AI_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.ctok.ai",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "ctok-ai-2",
    name: "CTok.ai",
    envKey: "CTOK_AI_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://ctok.ai",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "ctok-ai-3",
    name: "CTok.ai",
    envKey: "CTOK_AI_3_API_KEY",
    apiFormat: "gemini_native",
    baseUrl: "https://api.ctok.ai/v1beta",
    defaultModel: "gemini-2.5-flash",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "ctok-ai-openai",
    name: "CTok.ai",
    envKey: "CTOK_AI_OPENAI_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.ctok.ai",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "ctok-ai-v",
    name: "CTok.ai",
    envKey: "CTOK_AI_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.ctok.ai/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "cubence",
    name: "Cubence",
    envKey: "CUBENCE_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.cubence.com",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "cubence-2",
    name: "Cubence",
    envKey: "CUBENCE_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://cubence.com",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "cubence-3",
    name: "Cubence",
    envKey: "CUBENCE_3_API_KEY",
    apiFormat: "gemini_native",
    baseUrl: "https://api.cubence.com",
    defaultModel: "gemini-2.5-flash",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "cubence-openai",
    name: "Cubence",
    envKey: "CUBENCE_OPENAI_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.cubence.com",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "cubence-v",
    name: "Cubence",
    envKey: "CUBENCE_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.cubence.com/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "dmxapi",
    name: "DMXAPI",
    envKey: "DMXAPI_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://www.dmxapi.cn",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "dmxapi-2",
    name: "DMXAPI",
    envKey: "DMXAPI_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://www.dmxapi.cn",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "dmxapi-v",
    name: "DMXAPI",
    envKey: "DMXAPI_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://www.dmxapi.cn/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "e-flowcode",
    name: "E-FlowCode",
    envKey: "E_FLOWCODE_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://e-flowcode.cc",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
  },
  {
    id: "e-flowcode-2",
    name: "E-FlowCode",
    envKey: "E_FLOWCODE_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://e-flowcode.cc",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "e-flowcode-3",
    name: "E-FlowCode",
    envKey: "E_FLOWCODE_3_API_KEY",
    apiFormat: "gemini_native",
    baseUrl: "https://e-flowcode.cc",
    defaultModel: "gemini-2.5-flash",
    category: "aggregator",
  },
  {
    id: "e-flowcode-v",
    name: "E-FlowCode",
    envKey: "E_FLOWCODE_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://e-flowcode.cc/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "gemini-native",
    name: "Gemini Native",
    envKey: "GEMINI_NATIVE_API_KEY",
    apiFormat: "gemini_native",
    baseUrl: "https://generativelanguage.googleapis.com",
    defaultModel: "gemini-2.5-flash",
    category: "aggregator",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    envKey: "GITHUB_COPILOT_TOKEN",
    apiFormat: "openai_chat",
    baseUrl: "https://api.githubcopilot.com",
    defaultModel: "gpt-4o",
    category: "aggregator",
    hidden: true,
    requiresOAuth: true,
  },
  {
    id: "micu",
    name: "Micu",
    envKey: "MICU_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://www.micuapi.ai",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "micu-2",
    name: "Micu",
    envKey: "MICU_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://www.micuapi.ai",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "micu-v",
    name: "Micu",
    envKey: "MICU_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://www.micuapi.ai/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "novita-ai",
    name: "Novita AI",
    envKey: "NOVITA_AI_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.novita.ai/anthropic",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
  },
  {
    id: "novita-ai-2",
    name: "Novita AI",
    envKey: "NOVITA_AI_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://novita.ai",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "novita-ai-openai",
    name: "Novita AI",
    envKey: "NOVITA_AI_OPENAI_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.novita.ai/openai",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "novita-ai-openai-2",
    name: "Novita AI",
    envKey: "NOVITA_AI_OPENAI_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.novita.ai/v3/openai",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "nvidia",
    name: "Nvidia",
    envKey: "NVIDIA_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://integrate.api.nvidia.com",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "nvidia-v",
    name: "Nvidia",
    envKey: "NVIDIA_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    envKey: "OPENROUTER_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://openrouter.ai/api",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
  },
  {
    id: "openrouter-2",
    name: "OpenRouter",
    envKey: "OPENROUTER_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://openrouter.ai",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "openrouter-3",
    name: "OpenRouter",
    envKey: "OPENROUTER_3_API_KEY",
    apiFormat: "gemini_native",
    baseUrl: "https://openrouter.ai/api",
    defaultModel: "gemini-2.5-flash",
    category: "aggregator",
  },
  {
    id: "openrouter-v",
    name: "OpenRouter",
    envKey: "OPENROUTER_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://openrouter.ai/api/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "packycode",
    name: "PackyCode",
    envKey: "PACKYCODE_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://www.packyapi.com",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "packycode-2",
    name: "PackyCode",
    envKey: "PACKYCODE_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://www.packyapi.com",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "packycode-3",
    name: "PackyCode",
    envKey: "PACKYCODE_3_API_KEY",
    apiFormat: "gemini_native",
    baseUrl: "https://www.packyapi.com",
    defaultModel: "gemini-2.5-flash",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "packycode-v",
    name: "PackyCode",
    envKey: "PACKYCODE_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://www.packyapi.com/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "patewayai",
    name: "PatewayAI",
    envKey: "PATHWAY_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.pateway.ai",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "patewayai-2",
    name: "PatewayAI",
    envKey: "PATEWAYAI_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://pateway.ai",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "pipellm",
    name: "PIPELLM",
    envKey: "PIPELLM_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://cc-api.pipellm.ai",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
  },
  {
    id: "pipellm-2",
    name: "PIPELLM",
    envKey: "PIPELLM_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://code.pipellm.ai",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "pipellm-openai",
    name: "PIPELLM",
    envKey: "PIPELLM_OPENAI_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://cc-api.pipellm.ai",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "relaxycode",
    name: "RelaxyCode",
    envKey: "RELAXY_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://www.relaxycode.com",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
  },
  {
    id: "relaxycode-2",
    name: "RelaxyCode",
    envKey: "RELAXYCODE_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://www.relaxycode.com",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "rightcode",
    name: "RightCode",
    envKey: "RIGHTCODE_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://www.right.codes/claude",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "rightcode-2",
    name: "RightCode",
    envKey: "RIGHTCODE_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://www.right.codes",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "rightcode-claude",
    name: "RightCode",
    envKey: "RIGHTCODE_CLAUDE_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://www.right.codes/claude",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "rightcode-v",
    name: "RightCode",
    envKey: "RIGHTCODE_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://right.codes/codex/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "runapi",
    name: "RunAPI",
    envKey: "RUNAPI_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://runapi.co",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "runapi-2",
    name: "RunAPI",
    envKey: "RUNAPI_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://runapi.co",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "shengsuanyun",
    name: "Shengsuanyun",
    envKey: "SHENGSUAN_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://router.shengsuanyun.com/api",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "shengsuanyun-2",
    name: "Shengsuanyun",
    envKey: "SHENGSUANYUN_2_API_KEY",
    apiFormat: "gemini_native",
    baseUrl: "https://router.shengsuanyun.com/api",
    defaultModel: "gemini-2.5-flash",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "shengsuanyun-3",
    name: "Shengsuanyun",
    envKey: "SHENGSUANYUN_3_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://router.shengsuanyun.com/api/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "shengsuanyun-api",
    name: "Shengsuanyun",
    envKey: "SHENGSUANYUN_API_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://router.shengsuanyun.com/api",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "siliconflow",
    name: "SiliconFlow",
    envKey: "SILICONFLOW_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.siliconflow.cn",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "siliconflow-2",
    name: "SiliconFlow",
    envKey: "SILICONFLOW_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://siliconflow.cn",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "siliconflow-alt",
    name: "SiliconFlow en",
    envKey: "SILICONFLOW_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.siliconflow.com",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "siliconflow-alt-2",
    name: "SiliconFlow en",
    envKey: "SILICONFLOW_ALT_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://siliconflow.com",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "siliconflow-alt-v",
    name: "SiliconFlow en",
    envKey: "SILICONFLOW_ALT_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.siliconflow.com/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "siliconflow-v",
    name: "SiliconFlow",
    envKey: "SILICONFLOW_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.siliconflow.cn/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "sssaicode",
    name: "SSSAiCode",
    envKey: "SSSAI_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://node-hk.sssaicodeapi.com/api",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "sssaicode-2",
    name: "SSSAiCode",
    envKey: "SSSAICODE_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://sssaicodeapi.com",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "sssaicode-3",
    name: "SSSAiCode",
    envKey: "SSSAICODE_3_API_KEY",
    apiFormat: "gemini_native",
    baseUrl: "https://node-hk.sssaicodeapi.com/api",
    defaultModel: "gemini-2.5-flash",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "sssaicode-api",
    name: "SSSAiCode",
    envKey: "SSSAICODE_API_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://node-hk.sssaicodeapi.com/api",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "sssaicode-v",
    name: "SSSAiCode",
    envKey: "SSSAICODE_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://node-hk.sssaicodeapi.com/api/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "sudocode",
    name: "SudoCode",
    envKey: "SUDOCODE_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://sudocode.us",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
  },
  {
    id: "sudocode-2",
    name: "SudoCode",
    envKey: "SUDOCODE_2_API_KEY",
    apiFormat: "openai_responses",
    baseUrl: "https://sudocode.us",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "sudocode-3",
    name: "SudoCode",
    envKey: "SUDOCODE_3_API_KEY",
    apiFormat: "gemini_native",
    baseUrl: "https://sudocode.us",
    defaultModel: "gemini-2.5-flash",
    category: "aggregator",
  },
  {
    id: "sudocode-4",
    name: "SudoCode",
    envKey: "SUDOCODE_4_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://sudocode.us/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "therouter",
    name: "TheRouter",
    envKey: "THEROUTER_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.therouter.ai",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
  },
  {
    id: "therouter-2",
    name: "TheRouter",
    envKey: "THEROUTER_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://therouter.ai",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "therouter-3",
    name: "TheRouter",
    envKey: "THEROUTER_3_API_KEY",
    apiFormat: "gemini_native",
    baseUrl: "https://api.therouter.ai",
    defaultModel: "gemini-2.5-flash",
    category: "aggregator",
  },
  {
    id: "therouter-v",
    name: "TheRouter",
    envKey: "THEROUTER_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.therouter.ai/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "together-ai",
    name: "Together AI",
    envKey: "TOGETHER_AI_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.together.xyz/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
  },
  {
    id: "unity2-ai",
    name: "Unity2.ai",
    envKey: "UNITY2_API_KEY",
    apiFormat: "anthropic",
    baseUrl: "https://api.unity2.ai",
    defaultModel: "claude-3-5-sonnet-latest",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "unity2-ai-2",
    name: "Unity2.ai",
    envKey: "UNITY2_AI_2_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://unity2.ai",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "unity2-ai-3",
    name: "Unity2.ai",
    envKey: "UNITY2_AI_3_API_KEY",
    apiFormat: "gemini_native",
    baseUrl: "https://api.unity2.ai",
    defaultModel: "gemini-2.5-flash",
    category: "aggregator",
    isPartner: true,
  },
  {
    id: "unity2-ai-v",
    name: "Unity2.ai",
    envKey: "UNITY2_AI_V_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://api.unity2.ai/v1",
    defaultModel: "gpt-4o",
    category: "aggregator",
    isPartner: true,
  },
  // ──────────────── cloud (cloud-hosted proxies) ────────────────
  {
    id: "aws-bedrock",
    name: "AWS Bedrock",
    envKey: "AWS_BEDROCK_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://aws.amazon.com/bedrock/",
    defaultModel: "gpt-4o",
    category: "cloud",
    cloudProvider: "aws",
    hidden: true,
    requiresOAuth: false,
  },
  {
    id: "aws-bedrock-openai",
    name: "AWS Bedrock",
    envKey: "AWS_BEDROCK_OPENAI_API_KEY",
    apiFormat: "openai_chat",
    baseUrl: "https://bedrock-runtime.us-west-2.amazonaws.com",
    defaultModel: "gpt-4o",
    category: "cloud",
    cloudProvider: "aws",
    hidden: true,
    requiresOAuth: false,
  },
  {
    id: "ollama",
    name: "Ollama",
    envKey: "OLLAMA_ENABLED",
    apiFormat: "openai_chat",
    baseUrl: "http://localhost:11434/v1",
    defaultModel: "llama3.1",
    category: "custom",
  },
  {
    id: "lmstudio",
    name: "LM Studio",
    envKey: "LMSTUDIO_ENABLED",
    apiFormat: "openai_chat",
    baseUrl: "http://localhost:1234/v1",
    defaultModel: "qwen2.5-7b",
    category: "custom",
  },
  {
    id: "vllm",
    name: "vLLM",
    envKey: "VLLM_ENABLED",
    apiFormat: "openai_chat",
    baseUrl: "http://localhost:8000/v1",
    defaultModel: "meta-llama/Llama-3-8B-Instruct",
    category: "custom",
  },
]

/**
 * Build a stable lookup map: id → preset.
 */
export const PROVIDER_PRESETS_BY_ID: ReadonlyMap<string, ProviderPreset> = new Map(
  PROVIDER_PRESETS.map((p) => [p.id, p])
)

/**
 * Visible presets (excluding hidden OAuth / cloud placeholders).
 */
export const VISIBLE_PROVIDER_PRESETS: ProviderPreset[] = PROVIDER_PRESETS.filter(
  (p) => !p.hidden
)
